# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/bukkit-plugin.json

name: GriefAlert
version: 1.3
main: com.bzvzn.griefalert.GriefAlert
author: bzvzn
api-version: '26.2'
description: Informs ops and Discord if new players are using suspicious items
commands:
  gatp:
    description: Internal command to teleport to grief locations.
    permission: griefalert.notify
    usage: /gatp <world> <x> <y> <z>